spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: SQL@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1042561513781-etiukjevp2ucucqcod77j9fd45jvjeqp.apps.googleusercontent.com
            client-secret: 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
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

sql:
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: SQL@123
  driver_class_name: com.mysql.cj.jdbc.Driver
  hibernate_ddl_auto: update
  show_sql: true
  dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9191

management:
  endpoints:
    web:
      exposure:
        include: '*'